In [66]:
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
import pandas as pd
import joblib
from pso import calculate_profit, generate_particle_list, feasible_vec, demand, supply, dims, prod_cap, split_particles_list, rs, dims
from graph import SupplyChain

In [2]:
np.set_printoptions(suppress=True)

## Generate particles

Reduced demand

In [3]:
# particle_list3 = generate_particle_list(2000)

In [4]:
# joblib.dump(particle_list3, 'particle_list3')

Reduced supply

## Equillibrium  

In [5]:
# demand = sc.get_demand_vec()
# supply = sc.get_total_supply()
# profit = calculate_profit(demand, sup_cha=sc)
# profit -> 636366.0

## Reduced demand

In [6]:
# reduced_demand_filled = rd.fill_order()
# reduced_demand_profit = calculate_profit(reduced_demand_filled, rd)
# reduced_demand_profit -> 572729.4

## Reduced supply

In [7]:
reduced_supply_filled = rs.fill_order()
reduced_supply_profit = calculate_profit(reduced_supply_filled, rs)
reduced_supply_profit

558610.0

In [8]:
total_eggs_supplied = rs.get_supplied_eggs(reduced_supply_filled)
total_eggs_supplied

810000.0

In [9]:
np.sum(demand)

101970

In [11]:
dem_vec = rs.get_demand_vec()
sup_boxes = rs.get_boxes(dem_vec)
total_supply = rs.get_total_supply()

In [12]:
# for sb in rs.get_supply_boxes(rs.get_demand_vec()):
#     print(np.round(sb/(np.sum(rs.get_supply_boxes(rs.get_demand_vec()))), 3)) 

for sb in sup_boxes:
    print(np.round(sb/np.sum(sup_boxes),2), total_supply*np.round(sb/np.sum(sup_boxes),2)%6==0, total_supply*(sb/np.sum(sup_boxes)))

0.43 True 351262.1359223301
0.33 True 267378.64077669906
0.24 True 191359.22330097086


In [13]:
[int(total_supply*(sb/np.sum(sup_boxes))) for sb in sup_boxes]

[351262, 267378, 191359]

In [14]:
def allocate_supply_by_product(self) -> dict:
    dem_vec = self.get_demand_vec()
    dem_boxes = self.get_supply_boxes(dem_vec) # boxes
    total_supply = self.get_total_supply() # eggs
    eggs_qty = [int(total_supply*(db/np.sum(dem_boxes))) for db in dem_boxes]
    return {product:eggs for product, eggs in zip(self.products.keys(), eggs_qty)}


In [15]:
rs.get_total_supply()

810000

In [16]:
sup_boxes*rs.products['P1']

array([265320, 201960, 144540], dtype=int64)

In [17]:
351262.1359223301+267378.64077669906+191359.22330097086

810000.0

In [18]:
rs.products

{'P1': 6, 'P2': 10, 'P3': 12}

In [19]:
np.array([rs.graph[p][ c]['demand'] for p in  rs.products for c in rs.graph.successors(p) if p=='P1']) 

array([6600, 5500, 6600, 5500, 6600, 5500, 3300,  550,  550,  550,  550,
       1100,   22,   88,   44,  110,  110,   44,   88,   22,   22,   88,
         44,  110,   88,   44,   22,  110,   22,   88,   88,   66])

In [20]:
vec = np.array([1,2,3,4,5])
np.sum(vec)

15

In [32]:
# print(rs.get_demand_by_product('P1'))
supply_by_product = rs.allocate_supply_by_product()
supply_by_product['P1']

351262

In [37]:
rs.products.keys()

dict_keys(['P1', 'P2', 'P3'])

In [47]:
np.array([rs.graph[p][ c]['demand'] for p in  rs.products for c in rs.graph.successors(p) if p=='P2'])

array([6600, 3300, 5500, 4400, 6600, 3300, 1100,  220,  330,  330,  220,
       1100,   44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
         44,   44,   44,   44,   44,    0,    0,    0,    0,    0])

In [67]:
def set_up(pso_alg:PSO):
    pso = pso_alg()
    pso.initialise()
    pso.pick_informants_ring_topology()
    pso.calculate_fitness()
    pso.set_pbest()
    pso.set_lbest()
    pso.set_gbest()  
    pso.set_constricted_velocity()
    pso.move_random_back()


In [68]:
from cpso import CPSO

In [89]:
psos = (CPSO() for prod_name in rs.products.keys())

In [90]:
for p in psos:
    print(p.gbest_val)

-inf
-inf
-inf


In [91]:
for p in psos:
    p.initialise()
    # p.pick_informants_ring_topology()
    # p.calculate_fitness()
    # p.set_pbest()
    # p.set_lbest()
    # p.set_gbest()
    # p.set_constricted_velocity()
    # p.move_random_back()

In [92]:
for p in psos:
    print(p.gbest_val)